#!/bin/sh
#SBATCH --job-name="VAERMSD"
#SBATCH --output="VAE.%j.%N.out"
#SBATCH --partition=GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH --mem=22G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=jdepaoloboisvert@hawk.iit.edu
#SBATCH --account=mcb160011p
#SBATCH -t 00:15:00

source ~/.bashrc
module load anaconda3
module load cuda

source ~/.bashrc

conda activate jax_12

cd $SLURM_SUBMIT_DIR

python pyscripts/run_rollback_RMSD.py $1
