#!/bin/sh
#SBATCH --job-name="VAEviol"
#SBATCH --output="VAE.%j.%N.out"
#SBATCH --partition=GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH -n 5
#SBATCH --mail-type=END,FAIL,BEGIN
#SBATCH --mail-user=jdepaoloboisvert@hawk.iit.edu
#SBATCH --account=cis250004p
#SBATCH -t 24:00:00
#SBATCH --exclude=v020

source ~/.bashrc
module load anaconda3
module load cuda

source ~/.bashrc

conda activate jax_12

cd $SLURM_SUBMIT_DIR

python 02-write_viollin_data.py $1
